// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACSOvNoSK2pJHNm0fhgKcBnynA7RQZK7s',
    appId: '1:551703569960:web:d331e1c19a60630b3a371d',
    messagingSenderId: '551703569960',
    projectId: 'fire-base-c82a9',
    authDomain: 'fire-base-c82a9.firebaseapp.com',
    storageBucket: 'fire-base-c82a9.appspot.com',
    measurementId: 'G-XMFBT3RQM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5l-WeAcCma-GI9ICD0E7ktuNAtnMWS5Q',
    appId: '1:551703569960:android:47ae15fac6e2f2283a371d',
    messagingSenderId: '551703569960',
    projectId: 'fire-base-c82a9',
    storageBucket: 'fire-base-c82a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG5CYZMFQO2MZ7SbSFZCN8dd3Q8WqMMbw',
    appId: '1:551703569960:ios:6e2c4e6646df12b83a371d',
    messagingSenderId: '551703569960',
    projectId: 'fire-base-c82a9',
    storageBucket: 'fire-base-c82a9.appspot.com',
    iosBundleId: 'com.example.sms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG5CYZMFQO2MZ7SbSFZCN8dd3Q8WqMMbw',
    appId: '1:551703569960:ios:55ab86a7298184f83a371d',
    messagingSenderId: '551703569960',
    projectId: 'fire-base-c82a9',
    storageBucket: 'fire-base-c82a9.appspot.com',
    iosBundleId: 'com.example.sms.RunnerTests',
  );
}
